
---
version: '1'

# App (Project) name
name: Fx-Sample

# App description
description: Fx Testing.

# license
licenses:
  - APACHE LICENSE, VERSION 2.

imports:
  '@USName': FxLabs/Common/US-Names
  
  # SQL Injection Strings 
  '@GenericSQLInjections': FxLabs/Common/Generic-SQLInjections
  '@OracleSQLInjections': FxLabs/Common/Oracle-SQLInjections
  '@PostgresSQLInjections': FxLabs/Common/Postgres-SQLInjections
  '@SQLServerSQLInjections': FxLabs/Common/SQLServer-SQLInjections
  '@MySQLSQLInjections': FxLabs/Common/MySQL-SQLInjections
  
  # No-SQL DB Injection String
  '@MongoDBSQLInjections': FxLabs/Common/MongoDB-SQLInjections
  
  # Cross-Site Scripting Injection Strings
  '@XSSSQLInjections': FxLabs/Common/XSS
  

# App environments
environments:
  - name: UAT
    baseUrl: http://13.56.210.25/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: admin123$
  - name: Local
    baseUrl: http://localhost:8080/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: '{{@Vault.FxLabs/DevMachinePassword}}'
  - name: Dev
    baseUrl: http://localhost:8080/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: '{{@Vault.FxLabs/DevMachinePassword}}'
# Job profiles
jobs:
  - name: jobstg
    # refers the the env defined above
    environment: Stg
    tags:
      - V1
    # Bot regions - https://cloud.fxlabs.io/#/app/superbotnetwork
    regions: FXLabs/US_WEST_1
    # 0 15 10 ? * * -> Fire at 10:15am every day
    cron: '0 15 10 ? * *'
    issueTracker: 
      name: Stg-IssueTracker
      # e.g. https://github.com/shoukathmd/courseapo
      url: <<changeme>>
      account: Default_GitHub
    notifications: 
      - name: Dev-Slack-Notification
        channel: <<changeme>>
        account: Default_Slack
      - name: Dev-Email-Notification
        # enter your email
        to: <<changeme>>
        account: Default_Email
